HWID: "" 

Starting-Balance: 250

Remove-Armor-Kit: false

Block-Commands-In-Combat:
  - "/pv"
  - "/enderchest"
  - "/vault"
  - "/ec"
  - "/echest"
  - "/chest"
  
Combat-Tag:
   Time: 45
   Message: "&eYou are now spawn-tagged for &c{time} &eseconds."
   Disconnect: "&4&l{player} &chas been disconnected in combat."
   Block-Command: "&cYou cannot use that command with &4&lCombat-Tag"
   
Ender-Pearl:
   Time: 16
   Message:
      Remaining: "&cYou still have a &5&lEnderpearl &ccooldown for another &l{time}&c."
      Ended: "&eYour &5&lEnderpearl &ecooldown has expired."
   Name:
      Remaining: "&cEnderpearl cooldown: &f{time}"
      Ended: "&aEnderpearl cooldown ended."
      
Death:
   Money: 10
   Player-Message: "&c{killer} &ehas killer you."
   Killer-Message: "&eYou killed &c{player} &eand you have received &a${money}&e."
   
Destroy-The-Core:
   Started: "&6&l{dtc} &ehas been &astarted &eby &d{player}&e."
   Stopped: "&6&l{dtc} &ehas been &cstopped &eby &d{player}&e."
   Destroyed: "&d{player} &ehas destroyed a piece of &6&l{dtc} &7(&ePoints&7: &f{points}&7)"
   Destroyed-Core: "&6&l{dtc} &ehas been destroyed by &d{player}&e."
   Reward: "cr givekey {player} DTC 2"
   
Spawn:
   Time: 15
   Teleporting: "&eTeleporting to the spawn in &a{time} &eseconds."
   Teleport-Cancelled: "&cTeleporting has been cancelled."
   Already-Teleporting: "&cYou already teleporting..."
   Teleported: "&aYou has been teleported to spawn."
   Combat-Tag: "&cYou can't teleport to spawn if you have &4&lCombat-Tag&c."
   Set-Spawn: "&aSpawn location has been successfully set."
   
Scoreboard:
   Title: "&6&lFullPvP"
   Variables:
     Claims:
       PvP: #variables: {kills}, {deaths}, {balance}, {clan-info}
         - " &f\u00BB &eKills&7: &f{kills}"
         - " &f\u00BB &eDeaths&7: &f{deaths}"
       noPvP: #variables: {kills}, {deaths}, {balance}, {clan-info}
         - " &f\u00BB &eKills&7: &f{kills}"
         - " &f\u00BB &eDeaths&7: &f{deaths}"
         - " &f\u00BB &eBalance&7: &f{balance}"
         - "{clan-info}"
       Clan-info:
         - "&dClan &7\u00BB &9{name}"
         - "&dOnline &7\u00BB &f{members-online}/{max-members}"
     StaffMode:
       - "&6&lStaffMode"
       - " &f\u00BB &eVanished&7: {status}"
       - " &f\u00BB &ePlayers&7: &f{players}"
     DestroyTheCore:
       - "&6&lDTC"
       - " &f\u00BB &ePoints: &f{points-left}"
       - " &f\u00BB &eCoords: &f{x}, {y}, {z}"
     Claims:
       PvP: #variables: {kills}, {deaths}, {balance}, {clan-info}
         - " &f\u00BB &eKills&7: &f{kills}"
         - " &f\u00BB &eDeaths&7: &f{deaths}"
       noPvP: #variables: {kills}, {deaths}, {balance}, {clan-info}
         - " &f\u00BB &eKills&7: &f{kills}"
         - " &f\u00BB &eDeaths&7: &f{deaths}"
         - " &f\u00BB &eBalance&7: &f{balance}"
         - "{clan-info}"
       Clan-info:
         - "&dClan &7\u00BB &9{name}"
         - "&dOnline &7\u00BB &f{members-online}/{max-members}"
     Tournament:
       Title: "&6&l{event} Event"
       Sumo:
         Lines:
           - " &f\u00BB &dPlayers&7: &f{players}/{max-players}"
           - " &f\u00BB &dStarting&7: &f{countdown}"
         Waiting:
           - " &f\u00BB &dStatus&7: &fWaiting..."
         Fighting:
           - " &f\u00BB &dStatus&7: &fFighting..."
           - ""
           - "&5&l{first} &dVS &5&l{second}"
         Selecting:
           - " &f\u00BB &dStatus&7: &fSelecting..."
       FFA:
         Lines:
           - " &f\u00BB &dPlayers&7: &f{players}/{max-players}"
           - " &f\u00BB &dStarting&7: &f{countdown}"
         Waiting:
           - " &f\u00BB &dStatus&7: &fWaiting..."
         Invicibility: #Variables: {time}
           - " &f\u00BB &dStatus&7: &fInvincibility..."
         Fighting:
           - " &f\u00BB &dStatus&7: &fFighting..."
   Lines:
     - "&7&m--------------------------"
     - "{staffmode}"
     - "{claims}"
     - "&4&lCombat&7: &f{combat}"
     - "&9&lEnderpearl&7: {enderpearl}"
     - "&a&lSpawn&7: {spawn}"
     - "{tournament}"
     - ""
     - "&e&odiscord.gg/aRTsTHJ"
     - "&7&m--------------------------"