HWID: "" 

Starting-Balance: 250
Remove-Armor-Kit: false
DTC-Reward: "cr givekey {player} DTC 2"

Block-Commands-In-Combat:
  - "/pv"
  - "/enderchest"
  - "/vault"
  - "/ec"
  - "/echest"
  - "/chest"
  
Kill-Streak-Rewards:
  5:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  10:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  15:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  20:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  25:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  30:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  35:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  40:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  45:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  50:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  55:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  60:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  65:
    - "broadcast &eMensaje de prueba nick: {player} kills: {kills}"
    - "cr givekey {player} kill 1"
  
Combat-Tag:
   Time: 45
   Message: "&eYou are now spawn-tagged for &c{time} &eseconds."
   Disconnect: "&4&l{player} &chas been disconnected in combat."
   Block-Command: "&cYou cannot use that command with &4&lCombat-Tag"
   
Ender-Pearl:
   Time: 16
   Message:
      Remaining: "&cYou still have a &5&lEnderpearl &ccooldown for another &l{time}&c."
      Ended: "&eYour &5&lEnderpearl &ecooldown has expired."
   Name:
      Remaining: "&cEnderpearl cooldown: &f{time}"
      Ended: "&aEnderpearl cooldown ended."
      
Death:
   Money: 10
   Player-Message: "&c{killer} &ehas killer you."
   Killer-Message: "&eYou killed &c{player} &eand you have received &a${money}&e."
   
Spawn:
   Time: 15
   Teleporting: "&eTeleporting to the spawn in &a{time} &eseconds."
   Teleport-Cancelled: "&cTeleporting has been cancelled."
   Already-Teleporting: "&cYou already teleporting..."
   Teleported: "&aYou has been teleported to spawn."
   Combat-Tag: "&cYou can't teleport to spawn if you have &4&lCombat-Tag&c."
   Set-Spawn: "&aSpawn location has been successfully set."
   
Host-Menu:
  Title: "Host´s"
  Slots: 27
  items:
    1:
       Name: "&6&lSumo"
       Start-Command: "tournament create 24 Sumo"
       Winner-Command: "cr givekey {winner} Event 2"
       Permission: "fullpvp.tournament.sumo"
       Material: "STONE"
       Slot: 11
       Lore:
         - "&7&m-----------------------------------"
         - "&eDescripción sobre este evento&7:"
         - " &8* &7Lucha hasta que uno caiga!"
         - " &8* &7El ultimo que queda en pie gana!"
         - ""
         - "&ePremios del evento&7:"
         - " &8+&f2 &7Event Key"
         - ""
         - "&eClick para hostear el evento de &6&lSumo"
         - "&7&m-----------------------------------"
    2:
       Name: "&6&lFFA"
       Start-Command: "tournament create 64 FFA"
       Winner-Command: "cr givekey {winner} Event 2"
       Permission: "fullpvp.tournament.sumo"
       Material: "COBBLESTONE"
       Slot: 12
       Lore:
         - "&7&m-----------------------------------"
         - "&eDescripción sobre este evento&7:"
         - " &8* &7Todos contra todos!"
         - " &8* &7Se el mejor y se el ultimo en morir!"
         - ""
         - "&ePremios del evento&7:"
         - " &8+&f2 &7Event Key"
         - ""
         - "&eClick para hostear el evento de &6&lFFA"
         - "&7&m-----------------------------------"